class_system/accounts/urls.py
from django.urls import path
from django.conf import settings
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import views
from class_system.accounts.views import register
from class_system.accounts.views import dashboard

app_name = 'accounts'

company_context = {'company': settings.NAME_COMPANY}
context_login = {
    'extra_context': company_context,
    'authentication_form': AuthenticationForm,
    'template_name': 'login.html',
}
context_logout = {
    'extra_context': company_context,
    'next_page': 'core:home',
}

urlpatterns = [
    path('login/', views.LoginView.as_view(**context_login), name='login'),
    path('logout/', views.LogoutView.as_view(**context_logout), name='logout'),
    path('register/', register, name='register'),
    path('dashboard/', dashboard, name='dashboard'),
]

class_system/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('class_system.core.urls', namespace='core')),
    path('accounts/', include('class_system.accounts.urls', namespace='accounts')),
    path('classes/', include('class_system.classes.urls', namespace='classes')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

class_system/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, UserManager
import re
from django.core import validators


class User(AbstractBaseUser, PermissionsMixin):
    username = models.CharField('Usuário', max_length=30, unique=True,
                                validators=[validators.RegexValidator(re.compile('^[\w.@+-]+$'),
                                                                      'O nome de usuário só pode conter letras, digitos ou os '
                                                                      'seguintes caracteres: @/./+/-/_', 'invalid')]
                                )
    name = models.CharField('Nome', max_length=50, blank=True)
    email = models.EmailField('E-mail', unique=True)
    cpf = models.CharField('CPF', unique=True, max_length=12)
    cnpj_company = models.CharField('CNPJ da Empresa', max_length=14, blank=False)
    date_registration = models.DateField('Data de registro', auto_now_add=True)
    date_last_access = models.DateTimeField('Último acesso', blank=True, null=True)
    status = models.CharField('Status', default='Aguardando', max_length=30)

    is_staff = models.BooleanField('É da equipe?', blank=True, default=False)

    objects = UserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    def __str__(self):
        return self.name or self.username

    def get_short_name(self):
        return self.username

    def get_full_name(self):
        return str(self)

    class Meta:
        verbose_name = 'Usuário'
        verbose_name_plural = 'Usuários'

class_system/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

User = get_user_model()


class RegisterForm(forms.ModelForm):

    password1 = forms.CharField(label='Senha', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Confirmação de Senha', widget=forms.PasswordInput
    )

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError('A confirmação não está correta')
        return password2

    def save(self, commit=True):
        user = super(RegisterForm, self).save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        if commit:
            user.save()
        return user

    class Meta:
        model = User
        fields = ['username', 'email', 'name', 'cpf', 'cnpj_company']


class EditAccountForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['username', 'email', 'name']

class_system/accounts/views.py
from django.shortcuts import render, redirect
from django.conf import settings
from django.contrib.auth.decorators import login_required
from .forms import RegisterForm
from class_system.classes.models import Assisted


def register(request):
    context = {'company': settings.NAME_COMPANY}
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(settings.LOGIN_URL)
    else:
        form = RegisterForm()
    defaults = {
        'extra_context': context,
        'form': form,
    }
    return render(request, 'register.html', defaults)


@login_required
def dashboard(request):
    assisted = Assisted.objects.filter(user=request.user)
    context = {'company': settings.NAME_COMPANY, 'assisted': assisted}
    return render(request, 'dashboard.html', context)

class_system/accounts/templates/dashboard.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
    <meta name="keywords" content=""/>
    <meta name="description" content=""/>
    <link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600,700,900" rel="stylesheet"/>
    <link href="{% static 'css/default.css' %}" rel="stylesheet" type="text/css" media="all"/>
    <link href="{% static 'css/fonts.css' %}" rel="stylesheet" type="text/css" media="all"/>
</head>

<div id="newsletter">
    <h3>Informações da conta:</h3>
    <p><strong>User:</strong> {{ user }}</p>
    <p><strong>NOME:</strong> {{ user.name }} | <strong>E-mail:</strong> {{ user.email }} </p>
    <p><strong>CPF:</strong> {{ user.cpf }} | <strong>CNPJ EMPRESA:</strong> {{ user.cnpj_company }} </p>
    <p><strong>DATA DE REGISTRO:</strong> {{ user.date_registration }} | <strong>DATA DO ÚLTIMO ACESSO:</strong>
        {{ user.date_last_access }} </p>
    <p><strong>Status:</strong> {{ user.status }} </p>
</div>
<div>
    </p>
</div>
<div id="newsletter">
    <h3>Editar da conta:</h3>
    <p>Botão para nova senha</p>
    <p>Botão para alterar outras informações</p>
</div>
<div>
    </p>
</div>
<div id="newsletter">
    <h3>Aulas assistidas:</h3>
    {% for a in assisted %}
        <p><strong>{{a.classe}}</strong> - {{a.date_assisted}}</p>
    {% endfor %}
</div>
</html>

{% endblock %}

class_system/accounts/templates/login.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
    <meta name="keywords" content=""/>
    <meta name="description" content=""/>
    <link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600,700,900" rel="stylesheet"/>
    <link href="{% static 'css/default.css' %}" rel="stylesheet" type="text/css" media="all"/>
    <link href="{% static 'css/fonts.css' %}" rel="stylesheet" type="text/css" media="all"/>
</head>
<div id="newsletter">

    <h2>Login</h2>
    <div class="container">
        <form method="POST">
            {% csrf_token %}
            {% for f in form %}
                <div class="content">
                    {{ f.label_tag }}
                    {{ f }}
                    {{ f.errors }}
                    ____________________________________________________________________________
                </div>
            {% endfor %}
            <button class="button submit" type="submit">Login</button>
        </form>
    </div>
    <p></p>

    <a href="{% url 'accounts:register' %}" class="button submit" title="">Criar usuário!</a>

</div>
</html>

{% endblock %}

class_system/accounts/templates/register.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
    <meta name="keywords" content=""/>
    <meta name="description" content=""/>
    <link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600,700,900" rel="stylesheet"/>
    <link href="{% static 'css/default.css' %}" rel="stylesheet" type="text/css" media="all"/>
    <link href="{% static 'css/fonts.css' %}" rel="stylesheet" type="text/css" media="all"/>
</head>
<div id="newsletter">
    <h2>New user!</h2>
    <form method="POST">
        {% csrf_token %}
        {% for f in form %}
        <div class="content">
            {{ f.label_tag }}
            {{ f }}
            {{ f.errors }}
            ____________________________________________________________________
        </div>
        {% endfor %}
        <button class="button submit" type="submit">Salvar Usuário</button>
    </form>
</div>
</html>

{% endblock %}