class_system/accounts/urls.py
from django.urls import path
from django.conf import settings
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import views
from class_system.accounts.views import register
from class_system.accounts.views import dashboard

app_name = 'accounts'

company_context = {'company': settings.NAME_COMPANY}
context_login = {
    'extra_context': company_context,
    'authentication_form': AuthenticationForm,
    'template_name': 'login.html',
}
context_logout = {
    'extra_context': company_context,
    'next_page': 'core:home',
}

urlpatterns = [
    path('login/', views.LoginView.as_view(**context_login), name='login'),
    path('logout/', views.LogoutView.as_view(**context_logout), name='logout'),
    path('register/', register, name='register'),
    path('dashboard/', dashboard, name='dashboard'),
]

class_system/classes/urls.py
from django.urls import path
from class_system.classes.views import list_classes, assisted


app_name = 'classes'


urlpatterns = [
    path('list_classes/', list_classes, name='list_classes'),
    path('<slug:slug>', assisted, name='assisted'),
]

class_system/core/urls.py
from django.urls import path
from class_system.core.views import home, about, contact
import class_system

app_name = 'core'

urlpatterns = [
    path('', home, name='home'),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),
]

class_system/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('class_system.core.urls', namespace='core')),
    path('accounts/', include('class_system.accounts.urls', namespace='accounts')),
    path('classes/', include('class_system.classes.urls', namespace='classes')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

class_system/core/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

class_system/core/views.py
# -*- coding: utf-8 -*-

from django.http import HttpResponse
from django.shortcuts import render
from django.conf import settings

# Create your views here.


def home(request):
    context = {'company': settings.NAME_COMPANY}
    return render(request, 'home.html', context)


def about(request):
    context = {'company': settings.NAME_COMPANY}
    return render(request, 'about.html', context)


def contact(request):
    context = {'company': settings.NAME_COMPANY}
    return render(request, 'contact.html', context)

class_system/core/templates/about.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
    <meta name="keywords" content=""/>
    <meta name="description" content=""/>
    <link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600,700,900" rel="stylesheet"/>
    <link href="{% static 'css/default.css' %}" rel="stylesheet" type="text/css" media="all"/>
    <link href="{% static 'css/fonts.css' %}" rel="stylesheet" type="text/css" media="all"/>
</head>

<div id="newsletter">
    <h2>Descrição de como se da o funcionamento do sistema:</h2>
    <p>Foi baseado em uma regra de negócio onde a empresa 'test company' tem um sistema ERP e tem a necessidade de ter
        um material online para os funcionários de seus clientes.
    </p>

    <h4>Regras:</h4>
    <p>- Para acessar a plataforma de aulas o usuário deve se cadastrar informando o seu CPF e o CNPJ da empresa a qual
        trabalha.</p>

    <p>- O administrador deve confirmar que o usuário é funcionário da empresa em questão e realizar a liberação do seu
        usuário.</p>

    <p>- Após a liberação o usuário terá acesso as aulas onde ele pode escolher o tema e o sub-tema das aulas que
        deseja.</p>

    ------------------------------------------------------------------------------------------------------------------------------------------

    <h2>Description of how the system works:</h2>
    <p>It was based on a business rule where the test company has an ERP system and needs to have
        online material for your customers' employees.
    </p>

    <h4>Rules:</h4>
    <p>- To access the class platform the user must register by informing his CPF and CNPJ of the company to which
        works.</p>

    <p>- The administrator must confirm that the user is an employee of the company in question and release his
        user.</p>

    <p>- After the release, the user will have access to the classes where he can choose the theme and sub-theme of the
        classes that want.</p>
</div>
</html>

{% endblock %}

class_system/core/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
{% load static %}
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>{{ company }}</title>
    <meta charset="utf-8"/>
    <meta http-equiv="Content-Language" content="pt-br">
    <meta name="keywords" content=""/>
    <meta name="description" content=""/>
    <link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600,700,900" rel="stylesheet"/>
    <link href="default.css" rel="stylesheet" type="text/css" media="all"/>
    <link href="fonts.css" rel="stylesheet" type="text/css" media="all"/>

    <!--[if IE 6]>
    <link href="default_ie6.css" rel="stylesheet" type="text/css"/><![endif]-->

</head>
<body>
<div id="header-wrapper">
    <div id="header" class="container">
        <div id="logo">
            <h1><a href="{% url 'core:home' %}">{{ company }}</a></h1>
            <div id="menu">
                <ul>
                    <li><a href="{% url 'core:home' %}" accesskey="1" title="">Home</a></li>
                    <!--<li><a href="#" accesskey="2" title="">Our Clients</a></li>-->
                    <li><a href="{% url 'core:about' %}" accesskey="3" title="">About</a></li>
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'accounts:logout' %}" accesskey="4" title="">Logout</a></li>
                    <li><a href="{% url 'accounts:dashboard' %}" accesskey="6" title="">My account:{{user}}</a></li>
                    <li><a href="{% url 'classes:list_classes' %}" accesskey="7" title="">Classes</a></li>
                    {% else %}
                    <li><a href="{% url 'accounts:login' %}" accesskey="4" title="">Login</a></li>
                    {% endif %}
                    <li><a href="{% url 'core:contact' %}" accesskey="5" title="">Contact</a></li>
                </ul>
            </div>
        </div>
    </div>

    <div>
        {% block content %} {% endblock %}
    </div>

    <div id="copyright" class="container">
        <p>&copy; {{ company }} LTDA </p>
    </div>
</div>
</body>
</html>

class_system/core/templates/contact.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
    <meta name="keywords" content=""/>
    <meta name="description" content=""/>
    <link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600,700,900" rel="stylesheet"/>
    <link href="{% static 'css/default.css' %}" rel="stylesheet" type="text/css" media="all"/>
    <link href="{% static 'css/fonts.css' %}" rel="stylesheet" type="text/css" media="all"/>
</head>
<div id="newsletter">
Aqui vai as informações de contato
</div>
</html>

{% endblock %}

class_system/core/templates/home.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta name="keywords" content=""/>
    <meta name="description" content=""/>
    <link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600,700,900" rel="stylesheet"/>
    <link href="{% static 'css/default.css' %}" rel="stylesheet" type="text/css" media="all"/>
    <link href="{% static 'css/fonts.css' %}" rel="stylesheet" type="text/css" media="all"/>
</head>


<div id="wrapper3">
    <div id="portfolio" class="container">
        <div class="title">
            <h2>Portfolio</h2>
            <span class="byline">Integer sit amet pede vel arcu aliquet pretium</span>
        </div>
        <div class="column1">
            <div class="box"><a href="#"><img src="images/scr01.jpg" alt="" class="image image-full"/></a>
                <h3>Lorem Ipsum</h3>
                <p>Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...</p>
                <a href="#" class="button button-small">Etiam posuere</a>
            </div>
        </div>
        <div class="column2">
            <div class="box"><a href="#"><img src="images/scr01.jpg" alt="" class="image image-full"/></a>
                <h3>Lorem Ipsum</h3>
                <p>Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...</p>
                <a href="#" class="button button-small">Etiam posuere</a>
            </div>
        </div>
        <div class="column3">
            <div class="box"><a href="#"><img src="images/scr01.jpg" alt="" class="image image-full"/></a>
                <h3>Lorem Ipsum</h3>
                <p>Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...</p>
                <a href="#" class="button button-small">Etiam posuere</a>
            </div>
        </div>
        <div class="column4">
            <div class="box"><a href="#"><img src="images/scr01.jpg" alt="" class="image image-full"/></a>
                <h3>Lorem Ipsum</h3>
                <p>Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...</p>
                <a href="#" class="button button-small">Etiam posuere</a>
            </div>
        </div>
    </div>
</div>

</html>

{% endblock %}