class_system/classes/urls.py
from django.urls import path
from class_system.classes.views import list_classes, assisted


app_name = 'classes'


urlpatterns = [
    path('list_classes/', list_classes, name='list_classes'),
    path('<slug:slug>', assisted, name='assisted'),
]

class_system/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('class_system.core.urls', namespace='core')),
    path('accounts/', include('class_system.accounts.urls', namespace='accounts')),
    path('classes/', include('class_system.classes.urls', namespace='classes')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

class_system/classes/models.py
# -*- coding: utf-8 -*-
from django.db import models
from class_system.sub_theme.models import Sub_theme
from django.conf import settings


class ClassesManager(models.Manager):
    def search(self, query):
        return self.get_queryset().filter(
            models.Q(name_icontains=query) |
            models.Q(theme_icontains=query)
        )


class Classes(models.Model):
    title = models.CharField('Título', max_length=40)
    description = models.CharField('Descrição', max_length=150)
    creation_date = models.DateField('Data de criação', auto_now_add=True)
    slug = models.SlugField('slug')
    sub_theme = models.ForeignKey(Sub_theme, on_delete=models.SET(0))
    link = models.CharField('Link', max_length=150, default='')

    objects = ClassesManager

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Aula'
        verbose_name_plural = 'Aulas'
        ordering = ['title']


class Assisted(models.Model):
    STATUS_CHOICES = (
        (0, 'Iniciada'), (1, 'Acabada')
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name='user', related_name='assisted', on_delete=models.CASCADE)
    classe = models.ForeignKey(Classes, verbose_name='classe', related_name='assisted', on_delete=models.CASCADE)
    status = models.IntegerField('status', choices=STATUS_CHOICES, default=0, blank=True)
    date_assisted = models.DateField('Data que assistiu', auto_now_add=True)

    class Meta:
        verbose_name = 'Assistida'
        verbose_name_plural = 'Assistidas'
        unique_together = (('user', 'classe'),)

class_system/classes/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.conf import settings
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .models import Classes, Assisted
from class_system.theme.models import Theme
from class_system.sub_theme.models import Sub_theme


@login_required
def list_classes(request):
    classes = Classes.objects.all()
    theme = Theme.objects.all()
    sub_theme = Sub_theme.objects.all()
    context = {'company': settings.NAME_COMPANY,
               'classes': classes,
               'theme': theme,
               'sub_theme': sub_theme}
    return render(request, 'list_classes.html', context)


@login_required
def assisted(request, slug):
    classe = get_object_or_404(Classes, slug=slug)
    assisted, created = Assisted.objects.get_or_create(user=request.user, classe=classe)

    context = {'company': settings.NAME_COMPANY,
               'classe': classe}
    return render(request, 'details.html', context)

class_system/classes/templates/details.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
    <meta name="keywords" content=""/>
    <meta name="description" content=""/>
    <link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600,700,900" rel="stylesheet"/>
    <link href="{% static 'css/default.css' %}" rel="stylesheet" type="text/css" media="all"/>
    <link href="{% static 'css/fonts.css' %}" rel="stylesheet" type="text/css" media="all"/>
</head>
<div id="newsletter">
    <h1>{{classe.title}}</h1>
    <h3>Sub-tema: {{classe.sub_theme}}</h3>
    <h5>Data de criação: {{classe.creation_date}}</h5>
    <p>DESCRIÇÃO: {{classe.description}}</p>

    <iframe width="560" height="315" src="{{classe.link}}" frameborder="0"
            allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

</div>
</html>

{% endblock %}

class_system/classes/templates/list_classes.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
    <meta name="keywords" content=""/>
    <meta name="description" content=""/>
    <link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,600,700,900" rel="stylesheet"/>
    <link href="{% static 'css/default.css' %}" rel="stylesheet" type="text/css" media="all"/>
    <link href="{% static 'css/fonts.css' %}" rel="stylesheet" type="text/css" media="all"/>
</head>
{% for t in theme%}
    <div id="newsletter">
        <h1>{{t.name}}</h1>
    </div>
    <div>
        <p></p>
    </div>
    {% for s in sub_theme %}
        {% if s.theme == t %}
            <div id="newsletter">
                <h2>{{s.name}}</h2>
            </div>
            <div id="three-column" class="container">
                {% for c in classes%}
                        {% if c.sub_theme == s %}
                            <div>
                                <span class="arrow-down"></span>
                            </div>
                            <div id="tbox1"><span class="icon icon-wrench"></span>
                                <div class="title">
                                    <h2>{{c.title}}</h2>
                                </div>
                                <p>
                                    {{c.description}}
                                </p>
                                <a href="{% url 'classes:assisted' c.slug %}" class="button">Assistir</a>
                            </div>
                        {% endif %}
                {% endfor %}
            </div>
        {% endif %}
    {% endfor %}
{% endfor %}

</html>

{% endblock %}